openapi: 3.1.1
info:
  version: 1.0.0
  title: Campus Cribs
  description: This is a Campus Cribs contract implementation
paths:
  /post:
    get:
      summary: Get all posts information
      operationId: getPosts
      tags:
        - posts
      parameters:
        - name: tags
          in: query
          description: Tags to filter posts
          required: false
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/page"
      responses:
        "200":
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
  /search:
    get:
      summary: Search for posts and users
      operationId: searchPosts
      tags:
        - search
      parameters:
        - name: searchTerm
          in: query
          description: The search query
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/limit"
      responses:
        "200":
          description: A list of search results
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/SearchResponse"
components:
  schemas:
    SearchResults:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: "#/components/schemas/Post"
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the user
        username:
          type: string
          description: The username of the user
        thumbnail:
          type: string
          format: email
          description: Thumbnail of the user
    Post:
      type: object
      required:
        - id
        - thumbnail
        - price
      properties:
        id:
          type: string
          description: The unique identifier for the post
        thumbnail:
          type: string
          description: The URL of the thumbnail image
        price:
          type: number
          format: float
          description: The price of the post
    SearchResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/SearchResults"
  parameters:
    limit:
      description: to request with required page number or pagination
      in: query
      name: limit
      required: true
      schema:
        type: number
    page:
      description: to request with required page size
      in: query
      name: page
      required: false
      schema:
        type: number
