openapi: 3.1.1
info:
  version: 1.0.0
  title: CampusCribs
  description: CampusCribs API Implementation Specification
paths:
  /posts:
    get:
      summary: Get all posts
      operationId: getPosts
      tags:
        - posts
      parameters:
        - name: tags
          in: query
          description: Tags to filter posts
          required: false
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/page"
      responses:
        "200":
          description: An array of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
  /search:
    post:
      summary: Search for anything
      operationId: search
      tags:
        - search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          description: A search result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
components:
  schemas:
    SearchRequest:
      type: object
      properties:
        query:
          type: string
          description: The search query
        tags:
          type: array
          description: Tags to filter posts
          required: false
          items:
            type: string
            description: A tag
            required: false
    SearchResult:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: "#/components/schemas/SearchPost"
        users:
          type: array
          items:
            $ref: "#/components/schemas/SearchUser"
    SearchUser:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the user
        username:
          type: string
          description: The username of the user
        thumbnail:
          type: string
          description: Thumbnail of the user
    SearchPost:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the post
        thumbnail:
          type: string
          description: The URL of the thumbnail image
        price:
          type: number
          format: float
          description: The price of the post
        title:
          type: string
          description: The title of the post
    User:
      type: object
      properties:
        username:
          type: string
          description: The username of the user
        email:
          type: string
          description: The email of the user
        phone:
          type: string
          description: The phone number of the user
        firstName:
          type: string
          description: The first name of the user
        lastName:
          type: string
          description: The last name of the user
        bio:
          type: string
          description: The bio of the user
        thumbnail:
          type: string
          description: Thumbnail of the user
    Post:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the post
        thumbnail:
          type: string
          description: The URL of the thumbnail image
        title:
          type: string
          description: The title of the post
        roommates:
          type: string
          description: The number of roommates
        description:
          type: string
          description: The description of the post
        price:
          type: number
          format: float
          description: The price of the post
  parameters:
    limit:
      description: The limit of a paginated request
      in: query
      name: limit
      required: true
      schema:
        type: number
    page:
      description: The page of a paginated request
      in: query
      name: page
      required: false
      schema:
        type: number
