openapi: 3.1.1
info:
  version: 1.0.0
  title: Campus Cribs
  description: This is a Campus Cribs contract implementation
paths:
  /posts:
    get:
      summary: Get all posts information
      operationId: getPosts
      tags:
        - posts
      parameters:
        - name: tags
          in: query
          description: Tags to filter posts
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
components:
  schemas:
    Post:
      type: object
      required:
        - postid
        - thumbnail
        - price
      properties:
        postid:
          type: string
          description: The unique identifier for the post
        thumbnail:
          type: string
          description: The URL of the thumbnail image
        price:
          type: number
          format: float
          description: The price of the post
        location:
          type: string
          description: The location of the post
  parameters:
    limit:
      description: to request with required page number or pagination
      in: query
      name: limit
      required: true
      schema:
        type: number
    offset:
      description: to request with required page size
      in: query
      name: offset
      required: false
      schema:
        type: number
